/**
 * Spec-kit context loader.
 *
 * Reads spec-kit artifacts (constitution.md, plan.md, spec.md)
 * and produces a system prompt supplement that gives agents
 * the project context spec-kit generated during planning.
 */
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/** Paths to spec-kit artifacts relative to project root */
export interface SpecKitPaths {
  specsDir: string;
  constitutionPath: string | null;
  planPath: string | null;
  specPath: string | null;
  tasksPath: string | null;
}

/**
 * Detect spec-kit specs/ directory and locate artifacts.
 *
 * Spec-kit convention:
 *   specs/
 *     constitution.md
 *     spec.md
 *     plan.md
 *     tasks.md
 */
export function detectSpecKit(projectRoot: string): SpecKitPaths | null {
  const specsDir = join(projectRoot, "specs");
  if (!existsSync(specsDir)) return null;

  const tasksPath = join(specsDir, "tasks.md");
  if (!existsSync(tasksPath)) return null;

  return {
    specsDir,
    constitutionPath: existsSync(join(specsDir, "constitution.md"))
      ? join(specsDir, "constitution.md")
      : null,
    planPath: existsSync(join(specsDir, "plan.md"))
      ? join(specsDir, "plan.md")
      : null,
    specPath: existsSync(join(specsDir, "spec.md"))
      ? join(specsDir, "spec.md")
      : null,
    tasksPath,
  };
}

/**
 * Build a system prompt supplement from spec-kit artifacts.
 *
 * Injects constitution (principles), plan (architecture), and spec
 * (detailed requirements) into the agent's context so it can make
 * informed implementation decisions.
 */
export function buildSpecKitContext(paths: SpecKitPaths): string {
  const sections: string[] = [];

  if (paths.constitutionPath) {
    const content = readFileSync(paths.constitutionPath, "utf-8");
    sections.push(
      "## Project Constitution (Principles & Constraints)\n\n" + content.trim()
    );
  }

  if (paths.specPath) {
    const content = readFileSync(paths.specPath, "utf-8");
    sections.push(
      "## Specification\n\n" + content.trim()
    );
  }

  if (paths.planPath) {
    const content = readFileSync(paths.planPath, "utf-8");
    sections.push(
      "## Implementation Plan\n\n" + content.trim()
    );
  }

  if (sections.length === 0) return "";

  return (
    "# Spec-Kit Project Context\n\n" +
    "The following context was generated by spec-kit during the planning phase. " +
    "Use it to guide your implementation decisions.\n\n" +
    sections.join("\n\n---\n\n") +
    "\n"
  );
}
